M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Tue 03 Sep 2024 10:01:46 AM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-03T10:01:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X1.9651Y-5.2096
X2.0416Y-3.606
X2.3172Y-3.606
M30
